# vim: ft=yaml
os:
  - linux
  - osx

language: bash

sudo: required

env:
  - TRAVIS_BASH_VERSION="4.1" TRAVIS_ZSH_VERSION="5.0.0" TRAVIS_FISH_VERSION="2.2.0" TRAVIS_GIT_VERSION="1.8.5"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./tests/test-utils/installs/install-linux-deps.sh; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./tests/test-utils/installs/install-osx-deps.sh; fi;

install:
  - ssh-keygen -t rsa -N '' -f ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys

  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./tests/test-utils/installs/install-linux-pearl.sh; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./tests/test-utils/installs/install-osx-pearl.sh; fi;

  - echo 'PEARL_PACKAGES["sesaila"]={"url": "https://github.com/pearl-hub/sesaila.git"}' >> $HOME/.config/pearl/pearl.conf
  - echo 'PEARL_PACKAGES["dot-vim"]={"url": "https://github.com/pearl-hub/dot-vim.git"}' >> $HOME/.config/pearl/pearl.conf
  - echo 'PEARL_PACKAGES["dot-bash"]={"url": "https://github.com/pearl-hub/dot-bash.git"}' >> $HOME/.config/pearl/pearl.conf
  - echo "PEARL_PACKAGES[\"test\"]={\"url\": \"${PWD}\"}" >> ~/.config/pearl/pearl.conf

script:
  - hash -r
  - git --version
  - bash --version
  - zsh --version
  - fish --version
  - bash ./tests/test-utils/integ-tests/integ-tests.sh
  - zsh ./tests/test-utils/integ-tests/integ-tests.sh
  - fish ./tests/test-utils/integ-tests/integ-tests.fish
